AWSTemplateFormatVersion: "2010-09-09"
Description: "Template description"

Parameters:
  Env:
    Type: String
    Default: production
  
Outputs:
  TestEndpoint:
    Description: "endpoint"
    Value: !Sub "${Env}etests"
    Export:
      Name: !Sub 'endpoint-${Env}'
