AWSTemplateFormatVersion: "2010-09-09"
Description: "Template description"

Parameters:
  Env:
    Type: String
    Default: production
  
Outputs:
  ReportServiceApiEndpoint:
    Description: "Report-Service API endpoint"
    Value: !Sub "${Env}etests"
    Export:
      Name: !Sub 'um-report-service-endpoint-${Env}'
